/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",

    // Or if using `src` directory:
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        blueMain: "#33A0FF",
        OrangeMain: "#FFF3E4",
        btnOrange: "#F48c06",
        btnYagaan: "#ff6f4f",
        btnSmColor: "#f4c467",
        bgServiceColor: "#f8fbfb",
        BigTextColor: "#515577",
        Zaryellow1: "#F8EF7E",
        Zaryellow2: "#f8cf7e",
        footerTop1: "#EFAB3E",
        ZarGreen1: "#84DB7E",
        ZarGreen2: "#BDDB7E",
        footerTop1: "#EFAB3E",
        AboutTitle: "#2f327d",
        AboutDesriptionColor: "#696984",
        greengradient: "rgba(180deg, #36BC49 0%, #03A21A 100%)",
        // Gradient Color
        Zaryellow1: "#F8EF7E",
        Zaryellow2: "#f8cf7e",
        ZarGreen1: "#84DB7E",
        ZarGreen2: "#BDDB7E",
        DogColor1: "#E5F1F7",
        DogColor2: "#CCE3EC",
        DogTextColor: "#C1DFEC",
        CatColor1: "#FCF5D1",
        CatColor2: "#FBF2B9",
        CatTextColor: "#FBEEA6",
        RabbitColor1: "#F7f6f9",
        RabbitColor2: "#f4f6fa",
        RabbitTextColor: "#e9ecf2",
        BirdColor1: "#f7f9e1",
        BirdColor2: "#e9f4c6",
        BirdTextColor: "#dbe5bb",
        HedgehogColor1: "#FBF0F2",
        HedgehogColor2: "#F9EBEC",
        HedgehogTextColor: "#F9EBEC",
        footerTop1: "#EFAB3E",
        FishColor1: "#F0FBFD",
        FishColor2: "#E2ECFA",
        FishTextColor: "#D4E3FB",
        TurtleColor1: "#EBEEFB",
        TurtleColor2: "#DFE4F9",
        TurtleTextColor: "#D2D9F9",
        MouseColor: "#E9F7F6",
        MouseColor2: "#CEECEB",
        MouseTextColor: "#C0E7E5",
      },
    },
  },
  plugins: [],
};
